trigger:
- '*'

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - powershell: |
      Write-Host 'test ps variables'
      Write-Host $(Build.SourcesDirectory)
      Write-Host $(solution)
    displayName: 'Test PS variable'
