trigger:
- '*'

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - powershell: |
      $vsixManifestPath = Resolve-Path $(Build.SourcesDirectory)\src\SqlQueryTools\source.extension.vsixmanifest
      Write-Host "Vsix manifest path = $vsixManifestPath"
      Write-Host "##vso[task.setvariable variable=MyPsVar;]PsVarValueStep1"
    displayName: 'Test Set variable'
  - powershell: |
      Write-Host "My ps var = $(MyPsVar)"
    displayName: 'Test Get variable'
