// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlQueryTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlQueryTools.46119220-B112-4974-BF62-BA76F5548B13";
        public const string Name = "SqlQueryTools";
        public const string Description = @"Generate class with string based on Sql file content.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Gert Marginet";
        public const string Tags = "";
    }
}
