// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlQueryTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSqlQueryToolsPackageString = "113648a2-43ee-4c43-8914-6d9009fe90a8";
        public static Guid guidSqlQueryToolsPackage = new Guid(guidSqlQueryToolsPackageString);

        public const string guidSqlUIRuleString = "e5ac5a07-0c1e-426d-871b-c91db5f0ffb0";
        public static Guid guidSqlUIRule = new Guid(guidSqlUIRuleString);

        public const string guidSqlQueryToolsOutputPaneString = "47fd095c-4675-488c-87c0-495fddc87d7d";
        public static Guid guidSqlQueryToolsOutputPane = new Guid(guidSqlQueryToolsOutputPaneString);

        public const string guidSqlQueryToolsPackageCmdSetString = "8b06ca30-6835-4c11-bb15-4ad5d6ece351";
        public static Guid guidSqlQueryToolsPackageCmdSet = new Guid(guidSqlQueryToolsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SqlFileMenuGroup = 0x1020;
        public const int CustomToolCommandId = 0x0100;
        public const int AddSqlFileCommandId = 0x0200;
    }
}