using Dapper;
using EnvDTE;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using Microsoft.VisualStudio.TextTemplating.VSHost;
using SqlQueryTools.Config;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Text;
using SqlQueryTools.Helpers;
using SqlQueryTools.Dto;
using System.Linq;

namespace SqlQueryTools
{
    public sealed class SqlStringGenerator : BaseCodeGeneratorWithSite
    {
        public const string Name = nameof(SqlStringGenerator);
        public const string Description = "Generate class with string based on Sql file content.";

        public override string GetDefaultExtension()
        {
            return ".Generated.cs";
        }

        protected override byte[] GenerateCode(string inputFileName, string inputFileContent)
        {
            ThreadHelper.ThrowIfNotOnUIThread();

            var outputPane = GetSqlQueryToolsOutputPane();

            //outputPane.Clear();
            outputPane.Activate(); // Brings this pane into view
            outputPane.OutputString($"Generating code for {inputFileName}\r\n");

            var outputFileContentBuilder = new StringBuilder();
            outputFileContentBuilder.AppendLine($"//**************************************************************");
            outputFileContentBuilder.AppendLine($"// This code was generated by SqlQueryTools.SqlStringGenerator ");
            outputFileContentBuilder.AppendLine($"//**************************************************************");
            outputFileContentBuilder.AppendLine($"// Code is generated on: {DateTime.Now}");
            outputFileContentBuilder.AppendLine($"//**************************************************************");
            outputFileContentBuilder.AppendLine();
            outputFileContentBuilder.AppendLine();

            if (!(GlobalServiceProvider.GetService(typeof(DTE)) is DTE dte))
                throw new Exception($"Could not get service: {nameof(DTE)}");

            var inputProjectItem = dte.Solution.FindProjectItem(inputFileName);
            var project = inputProjectItem.ContainingProject;

            if (!SqlQueryToolsConfigHelper.GetConfig(project , out var config, out var errors))
            {
                foreach (var error in errors)
                {
                    outputPane.OutputString($"\t{error}\r\n");
                    outputFileContentBuilder.AppendLine($"//    {error}");
                }
                return Encoding.UTF8.GetBytes(outputFileContentBuilder.ToString());
            }

            var parameterDeclarations = "";
            var sqlCode = inputFileContent;
            if (inputFileContent.Contains(config.EndOfParameterDeclarationMarker))
            {
                if (config.GenerateParameterNames)
                {
                    parameterDeclarations = inputFileContent.Substring(0, inputFileContent.IndexOf(config.EndOfParameterDeclarationMarker, 0, StringComparison.InvariantCultureIgnoreCase) - 2);
                }
                sqlCode = inputFileContent.Substring(inputFileContent.IndexOf(config.EndOfParameterDeclarationMarker, 0, StringComparison.InvariantCultureIgnoreCase) + config.EndOfParameterDeclarationMarker.Length + 2);
            }

            List<SpDescribeFirstResultSetDto> queryMetaData;
            using (var cn = new SqlConnection(config.ConnectionString))
            {
                cn.Open();

                try
                {
                    queryMetaData = cn.Query<SpDescribeFirstResultSetDto>($"DECLARE @sql NVARCHAR(MAX) = '{sqlCode.Replace("'","''")}'; EXEC sp_describe_first_result_set @sql;").ToList();
                }
                catch (SqlException e)
                {
                    outputFileContentBuilder.AppendLine("// Class could not be generated due to the following parse errors:");
                    
                    foreach (SqlError sqlError in e.Errors)
                    {
                        if (sqlError.Number == 11529 || sqlError.Number == 11501) continue;

                        outputPane.OutputString($"\t{sqlError.Message}\r\n");
                        outputFileContentBuilder.AppendLine($"//    {sqlError.Message}");
                    }
                    
                    return Encoding.UTF8.GetBytes(outputFileContentBuilder.ToString());
                }
            }

            var className = Path.GetFileNameWithoutExtension(inputFileName);

            if (!System.CodeDom.Compiler.CodeGenerator.IsValidLanguageIndependentIdentifier(className))
            {
                outputFileContentBuilder.AppendLine($"//    {className} is not a valid class name.");

                outputPane.OutputString($"\t{className} is not a valid class name.\r\n");
                outputFileContentBuilder.AppendLine("// Class could not be generated due to the following parse errors:");
                
                return Encoding.UTF8.GetBytes(outputFileContentBuilder.ToString());
            }

            outputFileContentBuilder.AppendLine($"namespace {FileNamespace}");
            outputFileContentBuilder.AppendLine($"{{");
            outputFileContentBuilder.AppendLine($"\tpublic static class {className}");
            outputFileContentBuilder.AppendLine($"\t{{");
            outputFileContentBuilder.AppendLine($"\t\tpublic const string Sql = @\"{sqlCode}\";");

            if (config.GenerateParameterNames && parameterDeclarations.Length > 0)
            {
                var indexes = new Stack<int>();
                for (var i = 0; i < parameterDeclarations.Length; i++)
                {
                    switch (parameterDeclarations[i])
                    {
                        case '@':
                            indexes.Push(i);
                            break;
                        case ' ' when indexes.Count != 0:
                        {
                            var pos = indexes.Pop();
                            var len = i - 1 - pos;
                            var parameterName = parameterDeclarations.Substring(pos + 1, len);
                            parameterName = parameterName.Substring(0, 1).ToUpper() + parameterName.Substring(1);
                            outputFileContentBuilder.AppendLine();
                            outputFileContentBuilder.AppendLine($"\t\tpublic const string {parameterName} = @\"{parameterName}\";");
                            break;
                        }
                    }
                }
            }
            outputFileContentBuilder.AppendLine($"\t}}");

            if (config.GenerateResultDtoClass && queryMetaData.Count > 0)
            {
                outputFileContentBuilder.AppendLine();
                outputFileContentBuilder.AppendLine($"\tpublic class {className}Dto");
                outputFileContentBuilder.AppendLine($"\t{{");

                foreach (var columnInfo in queryMetaData)
                {
                    var columnName = columnInfo.name;
                    var columnType = SqlTypeHelper.ToCSharpTypeName(columnInfo.system_type_name);

                    outputFileContentBuilder.AppendLine($"\t\tpublic {columnType} {columnName} {{ get; set; }}");
                }

                outputFileContentBuilder.AppendLine($"\t}}");
            }

            outputFileContentBuilder.AppendLine($"}}");

            outputPane.OutputString($"\tCode generated successfully\r\n");

            return Encoding.UTF8.GetBytes(outputFileContentBuilder.ToString());
        }

        private IVsOutputWindowPane GetSqlQueryToolsOutputPane()
        {
            ThreadHelper.ThrowIfNotOnUIThread();

            if (!(GlobalServiceProvider.GetService(typeof(SVsOutputWindow)) is IVsOutputWindow outWindow))
                throw new Exception($"Could not get service: {nameof(SVsOutputWindow)}");

            outWindow.GetPane(ref PackageGuids.guidSqlQueryToolsOutputPane, out var outputPane);
            if (outputPane != null) return outputPane;

            outWindow.CreatePane(ref PackageGuids.guidSqlQueryToolsOutputPane, "Sql Query String Tools", 1, 1);
            outWindow.GetPane(ref PackageGuids.guidSqlQueryToolsOutputPane, out outputPane);

            return outputPane;
        }
    }
}