// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlQueryTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SqlQueryToolsString = "f3e8e45e-eff6-4b28-85e0-e6f5f9fa0d9f";
        public static Guid SqlQueryTools = new Guid(SqlQueryToolsString);

        public const string SqlQueryToolsMenuVisibilityConstraintString = "8f1fbdc1-de05-4ec8-be04-39d6c46dfdbd";
        public static Guid SqlQueryToolsMenuVisibilityConstraint = new Guid(SqlQueryToolsMenuVisibilityConstraintString);

        public const string IconsString = "f8cb65dd-6eae-4a35-a364-f5bb8bd1cea4";
        public static Guid Icons = new Guid(IconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SqlQueryToolsMenuGroup = 0x0001;
        public const int SqlQueryToolsMenu = 0x0002;
        public const int SqlQueryToolsCommandGroup = 0x0003;
        public const int AddSqlFileCommand = 0x0100;
        public const int Logo = 0x0001;
    }
}